using BoardGame.Api.Data;
using BoardGame.Api.Games.VayBat;
using BoardGame.Api.Platform;
using BoardGame.Api.Platform.Abstractions;
using BoardGame.Api.Services;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;

var builder = WebApplication.CreateBuilder(args);

// --- Database: PostgreSQL via EF Core ---
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Postgres")
        ?? "Host=localhost;Port=5432;Database=boardgame;Username=postgres;Password=postgres"));

// --- Cache: Redis ---
builder.Services.AddSingleton<IConnectionMultiplexer>(_ =>
{
    var conn = builder.Configuration.GetConnectionString("Redis") ?? "localhost:6379";
    var options = ConfigurationOptions.Parse(conn);
    // Không ném lỗi nếu Redis chưa sẵn sàng lúc khởi động — tự kết nối lại ngầm.
    options.AbortOnConnectFail = false;
    options.ConnectRetry = 5;
    options.ConnectTimeout = 5000;
    return ConnectionMultiplexer.Connect(options);
});
builder.Services.AddSingleton<RedisCacheService>();

// --- Queue: RabbitMQ ---
builder.Services.AddSingleton<RabbitMqPublisher>();

// --- Search: OpenSearch ---
builder.Services.AddSingleton<OpenSearchService>();

// --- Storage: MinIO ---
builder.Services.AddSingleton<MinioStorageService>();

// --- Game engines (mỗi boardgame = 1 IGameEngine; thêm game chỉ cần thêm 1 dòng) ---
builder.Services.AddSingleton<IGameEngine, VayBatEngine>();
builder.Services.AddSingleton<GameEngineRegistry>();

// --- Realtime: SignalR ---
builder.Services.AddSignalR();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
    options.AddDefaultPolicy(policy => policy
        .WithOrigins("http://localhost:5173")
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials()));

var app = builder.Build();

// Tạo/cập nhật schema idempotent bằng raw SQL — thay thế EnsureCreated() để tránh
// FormatException khi Npgsql parse introspection query phức tạp trên PostgreSQL 16.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "Greetings" (
            "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Message"   text NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "GameRooms" (
            "Id"          uuid PRIMARY KEY,
            "GameKey"     text NOT NULL DEFAULT '',
            "Status"      text NOT NULL,
            "RedPlayer"   text NULL,
            "WhitePlayer" text NULL,
            "Winner"      text NULL,
            "MapJson"     jsonb NOT NULL,
            "StateJson"   jsonb NOT NULL,
            "CreatedAt"   timestamp with time zone NOT NULL,
            "UpdatedAt"   timestamp with time zone NOT NULL
        );
        ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "GameKey"     text  NOT NULL DEFAULT '';
        ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "MapJson"     jsonb NOT NULL DEFAULT '{}'::jsonb;
        ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "StateJson"   jsonb NOT NULL DEFAULT '{}'::jsonb;
        ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "UpdatedAt"   timestamp with time zone NOT NULL DEFAULT now();
        ALTER TABLE "GameRooms" DROP COLUMN IF EXISTS "MaxRedTurns";

        CREATE TABLE IF NOT EXISTS "GameMoves" (
            "Id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RoomId"     uuid NOT NULL,
            "MoveNumber" integer NOT NULL,
            "Side"       text NOT NULL,
            "MoveJson"   jsonb NOT NULL,
            "CreatedAt"  timestamp with time zone NOT NULL
        );
        ALTER TABLE "GameMoves" ADD COLUMN IF NOT EXISTS "MoveJson"   jsonb   NOT NULL DEFAULT '{}'::jsonb;
        ALTER TABLE "GameMoves" ADD COLUMN IF NOT EXISTS "Side"       text    NOT NULL DEFAULT '';
        ALTER TABLE "GameMoves" ADD COLUMN IF NOT EXISTS "MoveNumber" integer NOT NULL DEFAULT 0;

        CREATE INDEX IF NOT EXISTS "IX_GameMoves_RoomId_MoveNumber"
            ON "GameMoves" ("RoomId", "MoveNumber");
        """);
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors();
app.MapControllers();
app.MapHub<GameHub>("/hubs/game");
app.MapGet("/health", () => Results.Ok(new { status = "healthy" }));

app.Run();
