using BoardGame.Api.Data;
using BoardGame.Api.Games.VayBat;
using BoardGame.Api.Platform;
using BoardGame.Api.Platform.Abstractions;
using BoardGame.Api.Services;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;

var builder = WebApplication.CreateBuilder(args);

// --- Database: PostgreSQL via EF Core ---
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Postgres")
        ?? "Host=localhost;Port=5432;Database=boardgame;Username=postgres;Password=postgres"));

// --- Cache: Redis ---
builder.Services.AddSingleton<IConnectionMultiplexer>(_ =>
{
    var conn = builder.Configuration.GetConnectionString("Redis") ?? "localhost:6379";
    var options = ConfigurationOptions.Parse(conn);
    // Không ném lỗi nếu Redis chưa sẵn sàng lúc khởi động — tự kết nối lại ngầm.
    options.AbortOnConnectFail = false;
    options.ConnectRetry = 5;
    options.ConnectTimeout = 5000;
    return ConnectionMultiplexer.Connect(options);
});
builder.Services.AddSingleton<RedisCacheService>();

// --- Queue: RabbitMQ ---
builder.Services.AddSingleton<RabbitMqPublisher>();

// --- Search: OpenSearch ---
builder.Services.AddSingleton<OpenSearchService>();

// --- Storage: MinIO ---
builder.Services.AddSingleton<MinioStorageService>();

// --- Game engines (mỗi boardgame = 1 IGameEngine; thêm game chỉ cần thêm 1 dòng) ---
builder.Services.AddSingleton<IGameEngine, VayBatEngine>();
builder.Services.AddSingleton<GameEngineRegistry>();

// --- Realtime: SignalR ---
builder.Services.AddSignalR();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
    options.AddDefaultPolicy(policy => policy
        .WithOrigins("http://localhost:5173")
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials()));

var app = builder.Build();

// Apply migrations / create the schema on startup (fine for a hello-world sample).
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.EnsureCreated(); // tạo schema nếu DB còn trống

    // EnsureCreated() không thêm bảng mới vào DB đã tồn tại (vd. DB cũ chỉ có Greetings).
    // Tạo các bảng game theo kiểu idempotent để chạy được cả DB mới lẫn DB cũ.
    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "GameRooms" (
            "Id" uuid PRIMARY KEY,
            "GameKey" text NOT NULL,
            "Status" text NOT NULL,
            "RedPlayer" text NULL,
            "WhitePlayer" text NULL,
            "Winner" text NULL,
            "MapJson" jsonb NOT NULL,
            "StateJson" jsonb NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL
        );
        CREATE TABLE IF NOT EXISTS "GameMoves" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "RoomId" uuid NOT NULL,
            "MoveNumber" integer NOT NULL,
            "Side" text NOT NULL,
            "MoveJson" jsonb NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_GameMoves_RoomId_MoveNumber"
            ON "GameMoves" ("RoomId", "MoveNumber");
        """);
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors();
app.MapControllers();
app.MapHub<GameHub>("/hubs/game");
app.MapGet("/health", () => Results.Ok(new { status = "healthy" }));

app.Run();
