using BoardGame.Api.Data;
using BoardGame.Api.Games.VayBat;
using BoardGame.Api.Platform;
using BoardGame.Api.Platform.Abstractions;
using BoardGame.Api.Platform.Auth;
using BoardGame.Api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;

var builder = WebApplication.CreateBuilder(args);

// --- Database: PostgreSQL via EF Core ---
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Postgres")
        ?? "Host=localhost;Port=5432;Database=boardgame;Username=postgres;Password=postgres"));

// --- Cache: Redis ---
builder.Services.AddSingleton<IConnectionMultiplexer>(_ =>
{
    var conn = builder.Configuration.GetConnectionString("Redis") ?? "localhost:6379";
    var options = ConfigurationOptions.Parse(conn);
    options.AbortOnConnectFail = false;
    options.ConnectRetry = 5;
    options.ConnectTimeout = 5000;
    return ConnectionMultiplexer.Connect(options);
});
builder.Services.AddSingleton<RedisCacheService>();

// --- Queue: RabbitMQ ---
builder.Services.AddSingleton<RabbitMqPublisher>();

// --- Search: OpenSearch ---
builder.Services.AddSingleton<OpenSearchService>();

// --- Storage: MinIO ---
builder.Services.AddSingleton<MinioStorageService>();

// --- Game engines ---
builder.Services.AddSingleton<IGameEngine, VayBatEngine>();
builder.Services.AddSingleton<GameEngineRegistry>();

// --- Auth: đăng nhập OTP qua Gmail, JWT trong cookie HttpOnly ---
builder.Services.AddSingleton<GmailOtpSender>();
builder.Services.AddSingleton<TokenService>();
builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        var tokens = new TokenService(builder.Configuration);
        options.TokenValidationParameters = tokens.ValidationParameters;
        options.Events = new JwtBearerEvents
        {
            // Token nằm trong cookie HttpOnly (JS không đọc được — chống XSS).
            // Vẫn nhận Authorization header cho tool/test; SignalR dùng cookie tự động.
            OnMessageReceived = ctx =>
            {
                if (string.IsNullOrEmpty(ctx.Token) &&
                    ctx.Request.Cookies.TryGetValue(TokenService.CookieName, out var cookie))
                    ctx.Token = cookie;
                return Task.CompletedTask;
            },
        };
    });
builder.Services.AddAuthorization();

// --- Realtime: SignalR ---
builder.Services.AddSignalR();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
    options.AddDefaultPolicy(policy => policy
        .WithOrigins("http://localhost:5173")
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials()));

var app = builder.Build();

// Mỗi câu SQL chạy riêng — Npgsql extended protocol không cho phép nhiều lệnh
// trong một lần gọi, cần tách ra. Retry xử lý race giữa healthcheck và sẵn sàng thực.
string[] schemaSqls =
[
    """
    CREATE TABLE IF NOT EXISTS "Greetings" (
        "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Message"   text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS "GameRooms" (
        "Id"          uuid PRIMARY KEY,
        "GameKey"     text NOT NULL DEFAULT '',
        "Status"      text NOT NULL,
        "RedPlayer"   text NULL,
        "WhitePlayer" text NULL,
        "Winner"      text NULL,
        "MapJson"     jsonb NOT NULL DEFAULT '{{}}'::jsonb,
        "StateJson"   jsonb NOT NULL DEFAULT '{{}}'::jsonb,
        "CreatedAt"   timestamp with time zone NOT NULL,
        "UpdatedAt"   timestamp with time zone NOT NULL DEFAULT now()
    )
    """,
    """ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "GameKey"   text  NOT NULL DEFAULT ''""",
    """ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "MapJson"   jsonb NOT NULL DEFAULT '{{}}'::jsonb""",
    """ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "StateJson" jsonb NOT NULL DEFAULT '{{}}'::jsonb""",
    """ALTER TABLE "GameRooms" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now()""",
    """ALTER TABLE "GameRooms" DROP COLUMN IF EXISTS "MaxRedTurns" """,
    """
    CREATE TABLE IF NOT EXISTS "GameMoves" (
        "Id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "RoomId"     uuid NOT NULL,
        "MoveNumber" integer NOT NULL DEFAULT 0,
        "Side"       text NOT NULL DEFAULT '',
        "MoveJson"   jsonb NOT NULL DEFAULT '{{}}'::jsonb,
        "CreatedAt"  timestamp with time zone NOT NULL
    )
    """,
    """ALTER TABLE "GameMoves" DROP COLUMN IF EXISTS "PieceId" """,
    """ALTER TABLE "GameMoves" ADD COLUMN IF NOT EXISTS "MoveJson"   jsonb   NOT NULL DEFAULT '{{}}'::jsonb""",
    """ALTER TABLE "GameMoves" ADD COLUMN IF NOT EXISTS "Side"       text    NOT NULL DEFAULT ''""",
    """ALTER TABLE "GameMoves" ADD COLUMN IF NOT EXISTS "MoveNumber" integer NOT NULL DEFAULT 0""",
    """CREATE INDEX IF NOT EXISTS "IX_GameMoves_RoomId_MoveNumber" ON "GameMoves" ("RoomId", "MoveNumber")""",
    """CREATE UNIQUE INDEX IF NOT EXISTS "UX_GameMoves_RoomId_MoveNumber" ON "GameMoves" ("RoomId", "MoveNumber")""",
    """
    CREATE TABLE IF NOT EXISTS "Users" (
        "Id"          uuid PRIMARY KEY,
        "Email"       text NOT NULL DEFAULT '',
        "DisplayName" text NOT NULL DEFAULT '',
        "CreatedAt"   timestamp with time zone NOT NULL DEFAULT now(),
        "LastLoginAt" timestamp with time zone NULL
    )
    """,
    """CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Email" ON "Users" ("Email")""",
    """
    CREATE TABLE IF NOT EXISTS "AuthOtps" (
        "Id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "Email"      text NOT NULL DEFAULT '',
        "CodeHash"   text NOT NULL DEFAULT '',
        "ExpiresAt"  timestamp with time zone NOT NULL DEFAULT now(),
        "Attempts"   integer NOT NULL DEFAULT 0,
        "ConsumedAt" timestamp with time zone NULL,
        "CreatedAt"  timestamp with time zone NOT NULL DEFAULT now()
    )
    """,
    """CREATE INDEX IF NOT EXISTS "IX_AuthOtps_Email" ON "AuthOtps" ("Email")""",
];

using (var scope = app.Services.CreateScope())
{
    var db     = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();

    // Mỗi statement chạy trong try-catch riêng — một statement thất bại không
    // chặn các statement sau. Retry toàn bộ tập nếu có lỗi (thường là DB chưa sẵn sàng).
    for (var attempt = 1; attempt <= 10; attempt++)
    {
        var errors = new List<string>();
        foreach (var sql in schemaSqls)
        {
            try { db.Database.ExecuteSqlRaw(sql); }
            catch (Exception ex) { errors.Add(ex.Message.Split('\n')[0]); }
        }

        if (errors.Count == 0)
        {
            logger.LogInformation("Schema bootstrap hoàn tất (lần {Attempt}).", attempt);
            break;
        }

        if (attempt < 10)
        {
            logger.LogWarning("Schema bootstrap lần {Attempt}: {N} lỗi, thử lại sau 5s…\n{Errors}",
                attempt, errors.Count, string.Join("\n", errors));
            await Task.Delay(5_000);
        }
        else
        {
            var msg = $"Schema bootstrap thất bại sau 10 lần:\n{string.Join("\n", errors)}";
            logger.LogCritical(msg);
            throw new InvalidOperationException(msg);
        }
    }
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapHub<GameHub>("/hubs/game");
app.MapGet("/health", () => Results.Ok(new { status = "healthy" }));

app.Run();
